services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - PYTHONPATH=/app  # <-- Add this line
